spring:
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  datasource:
    url: jdbc:mysql://localhost:3306/project_matcher_db
    username: project_matcher_db
    password: project_matcher_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 3
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        enable_lazy_load_no_trans: true
  security:
    filter:
      order: 10
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: nguyenthanhnamtb2002@gmail.com
#    password: sgqm qldt zvgm xmxb
#    default-encoding: UTF-8
#    properties:
#      mail:
#        mime:
#          charset: UTF
#        smtp:
#          auth: true
#          starttls:
#            enable: true

logging:
  config: config/log4j2.xml

jwt:
  secret: mM^YA2nAsbpGhHRcqfrp#&sAVs!d9794#6Xdvf4W7N**J@c&&a4e*#kTpSZnVcpyZWBu

server:
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024